fragment InvestmentParts on Investment {
  title
  number
  properties_count
  description
  availability
  body
}

fragment PropertiesParts on Properties {
  title
  investment_number
  type
  square_meters
  plot_square_meters
  availability
  reservation
  price
  body
}

fragment NewsParts on News {
  title
  description
  body
}
